### ISSUE TITLE
HackerTab for Opera GX

### ISSUE THREAD

**Issue by ghost** [FahadYousafMahar/HackerTab#1]
Hi, I love this chrome extension, I've been using it for about 3 years now. I'm starting to use Opera browser and want to know how to use this on that platform, it's not available on Opera add-ons, and when I install it, it doesn't load. 

Thank you and thank you for this awesome extension!

**Comment by FahadYousafMahar** [comment]
[Add Chrome extensions to Opera](https://help.opera.com/en/latest/customization/)

To install extensions from the Google Chrome webstore into Opera, you must first download and install the Install Chrome extensions addon from the [Opera addons store](https://addons.opera.com/en/extensions/details/install-chrome-extensions/).

Once you’ve installed the Install Chrome extensions addon, you can go to the[ Chrome extensions webstore](https://chrome.google.com/webstore/category/extensions) and choose the extension you want. Click the Add to Opera button and follow the prompts. You will be taken to your extensions manager page where you can click Install. After adding chrome extensions to your Opera browser, you can use them right away.
